// All app data is kept here. Cart and orders are saved in the browser using localStorage.
const restaurants=[
 {id:1,name:'Pizza Palace',cuisine:'Pizza, Italian',time:'25 min',icon:'🍕',menu:[['Margherita Pizza',249],['Farmhouse Pizza',349],['Garlic Bread',129]]},
 {id:2,name:'Burger Barn',cuisine:'Burgers, Fast Food',time:'20 min',icon:'🍔',menu:[['Classic Veg Burger',159],['Cheese Burger',199],['French Fries',99]]},
 {id:3,name:'Spice Route',cuisine:'Indian, Biryani',time:'30 min',icon:'🍛',menu:[['Veg Biryani',220],['Paneer Butter Masala',260],['Butter Naan',45]]}
];
const getCart=()=>JSON.parse(localStorage.getItem('quickbiteCart')||'[]');
const saveCart=cart=>localStorage.setItem('quickbiteCart',JSON.stringify(cart));
const money=n=>'₹'+n;
function updateCount(){const el=document.querySelector('#cart-count');if(el)el.textContent=getCart().reduce((n,item)=>n+item.qty,0)}
function add(item){let cart=getCart(),found=cart.find(x=>x.name===item.name);if(found)found.qty++;else cart.push({...item,qty:1});saveCart(cart);updateCount();alert(item.name+' added to cart')}
function totals(){const sub=getCart().reduce((n,x)=>n+x.price*x.qty,0),delivery=sub?40:0,tax=Math.round(sub*.05);return{sub,delivery,tax,total:sub+delivery+tax}}
function renderHome(){const box=document.querySelector('#restaurants');if(!box)return;const draw=filter=>box.innerHTML=restaurants.filter(r=>(r.name+r.cuisine).toLowerCase().includes(filter)).map(r=>`<a class="card" href="restaurant.html?id=${r.id}"><div class="emoji">${r.icon}</div><h3>${r.name}</h3><p class="tag">${r.cuisine}</p><b>★ 4.5</b> · ${r.time}</a>`).join('')||'<p>No restaurant found.</p>';draw('');document.querySelector('#search').oninput=e=>draw(e.target.value.toLowerCase())}
function renderRestaurant(){const menu=document.querySelector('#menu');if(!menu)return;const r=restaurants.find(x=>x.id===Number(new URLSearchParams(location.search).get('id'))) || restaurants[0];document.querySelector('#restaurant-info').innerHTML=`<div class="emoji">${r.icon}</div><h1>${r.name}</h1><p>${r.cuisine} · ★ 4.5 · ${r.time}</p>`;menu.innerHTML=r.menu.map(([name,price])=>`<article class="menu-item"><div><h3>${name}</h3><span class="price">${money(price)}</span></div><button data-name="${name}" data-price="${price}">Add</button></article>`).join('');menu.onclick=e=>{if(e.target.tagName==='BUTTON')add({name:e.target.dataset.name,price:Number(e.target.dataset.price),restaurant:r.name})}}
function renderCart(){const list=document.querySelector('#cart-items'),summary=document.querySelector('#cart-summary');if(!list)return;const cart=getCart();if(!cart.length){list.innerHTML='<p class="empty">Your cart is empty. Tiny tragedy. <a href="index.html">Find food</a></p>';summary.innerHTML='';return}list.innerHTML=cart.map((x,i)=>`<article class="cart-row"><div><b>${x.name}</b><br><span class="tag">${x.restaurant} · ${money(x.price)}</span></div><div class="quantity"><button data-action="minus" data-i="${i}">−</button>${x.qty}<button data-action="plus" data-i="${i}">+</button><button class="remove" data-action="remove" data-i="${i}">Remove</button></div></article>`).join('');const t=totals();summary.innerHTML=`<p><span>Subtotal</span><span>${money(t.sub)}</span></p><p><span>Delivery</span><span>${money(t.delivery)}</span></p><p><span>Tax</span><span>${money(t.tax)}</span></p><p class="total"><span>Total</span><span>${money(t.total)}</span></p><a href="checkout.html"><button>Proceed to checkout</button></a>`;list.onclick=e=>{let i=e.target.dataset.i;if(i===undefined)return;let c=getCart();if(e.target.dataset.action==='plus')c[i].qty++;if(e.target.dataset.action==='minus'&&c[i].qty>1)c[i].qty--;if(e.target.dataset.action==='remove')c.splice(i,1);saveCart(c);updateCount();renderCart()}}
function checkout(){const form=document.querySelector('#checkout-form');if(!form)return;if(!getCart().length){location='cart.html';return}form.onsubmit=e=>{e.preventDefault();if(!form.checkValidity()){document.querySelector('#form-error').textContent='Please complete the fields correctly.';return}let orders=JSON.parse(localStorage.getItem('quickbiteOrders')||'[]');let order={id:Date.now(),date:new Date().toLocaleString(),customer:Object.fromEntries(new FormData(form)),items:getCart(),total:totals().total,status:'Order placed'};orders.unshift(order);localStorage.setItem('quickbiteOrders',JSON.stringify(orders));localStorage.setItem('quickbiteLastOrder',JSON.stringify(order));saveCart([]);location='confirmation.html'}}
function confirmation(){const box=document.querySelector('#confirmation');if(!box)return;const o=JSON.parse(localStorage.getItem('quickbiteLastOrder')||'null');if(!o){box.innerHTML='<h1>No recent order</h1><a href="index.html">Order something tasty</a>';return}box.innerHTML=`<h1>Order confirmed! 🎉</h1><p>Order #${String(o.id).slice(-6)} · ${money(o.total)}</p><p class="status" id="status">Order placed</p><p id="track">Restaurant is preparing your food.</p><a href="orders.html"><button>View orders</button></a>`;let stages=[['Restaurant is preparing your food.','Preparing'],['Your rider has picked it up.','On the way'],['Delivered. Bon appétit!','Delivered']],i=0;setInterval(()=>{if(i<stages.length){document.querySelector('#track').textContent=stages[i][0];document.querySelector('#status').textContent=stages[i++][1]}},3500)}
function renderOrders(){const box=document.querySelector('#orders');if(!box)return;let orders=JSON.parse(localStorage.getItem('quickbiteOrders')||'[]');box.innerHTML=orders.length?orders.map(o=>`<article class="order"><h3>Order #${String(o.id).slice(-6)} <span class="status">${o.status}</span></h3><p>${o.items.map(x=>x.name+' × '+x.qty).join(', ')}</p><b>${money(o.total)}</b> · <span class="tag">${o.date}</span></article>`).join(''):'<p class="empty">No orders yet. The kitchen is suspiciously quiet.</p>'}
updateCount();renderHome();renderRestaurant();renderCart();checkout();confirmation();renderOrders();
